[platformio]
default_envs = ZuluSCSI_RP2040

[env]
# Paramètres globaux
build_flags =
    -DBUILD_ENV=$PIOENV

[env:ZuluSCSI_RP2MCU]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#6164ed92d83c1241a1d84ad848158d7b0fb486e3
framework = arduino
platform_packages =
    framework-arduinopico@https://github.com/rabbitholecomputing/arduino-pico.git#v5.4.2-DaynaPORT
extra_scripts =
    src/build_bootloader.py
lib_deps =
    https://github.com/rabbitholecomputing/RP2350_Logic_Sniffer#1.0.1
    compact25519=https://github.com/rabbitholecomputing/compact25519
    adafruit/Adafruit SSD1306@^2.5.15
    adafruit/Adafruit GFX Library@^1.12.1
    adafruit/Adafruit BusIO@^1.17.1
    ZuluSCSI_UI_RP2MCU
    ZuluSCSI_audio_RP2MCU
build_flags =
    ${env.build_flags}

[env:ZuluSCSI_RP2040]
extends = env:ZuluSCSI_RP2MCU
board = rpipico
board_build.core = earlephilhower
board_build.filesystem_size = 0M
build_flags =
    ${env:ZuluSCSI_RP2MCU.build_flags}
    -DZULUSCSI_MCU_RP2040
    -DCONTROL_BOARD
    -DSSD1306_NO_SPLASH
    -Wno-switch
# Ces deux-là sont les briques qui manquaient tout à l'heure
ldscript_bootloader = src/rp2040-bootloader.ld
linker_script_template = src/rp2040-template.ld
