; PlatformIO Project Configuration File - Nettoyé pour ZuluSCSI RP2040
; Optimisé pour une compilation rapide via GitHub Actions

[platformio]
# On ne garde que ton environnement cible ici
default_envs = ZuluSCSI_RP2040

[env]
build_flags =
    -DBUILD_ENV=$PIOENV

[env:ZuluSCSI_RP2MCU]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#6164ed92d83c1241a1d84ad848158d7b0fb486e3
platform_packages =
    framework-arduinopico@https://github.com/rabbitholecomputing/arduino-pico.git#v5.4.2-DaynaPORT
extra_scripts =
    src/build_bootloader.py
lib_deps =
    https://github.com/rabbitholecomputing/RP2350_Logic_Sniffer#1.0.1
    compact25519=https://github.com/rabbitholecomputing/compact25519
    adafruit/Adafruit SSD1306@^2.5.15
    adafruit/Adafruit GFX Library@^1.12.1
    adafruit/Adafruit BusIO@^1.17.1
    ZuluSCSI_UI_RP2MCU
    ZuluSCSI_audio_RP2MCU
build_flags =
    ${env.build_flags}
    -DUSBD_VID=0x16D0
    -DUSBD_PID=0x120E
    -DUSB_MANUFACTURER='"Rabbit Hole Computing"'
    -DUSB_PRODUCT='"ZuluSCSI RP2040"'
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_EXCEPTIONS
    -DARM_MATH_CM0PLUS
    -DNDEBUG

[env:ZuluSCSI_RP2040]
extends = env:ZuluSCSI_RP2MCU
board = rpipico
board_build.core = earlephilhower
board_build.filesystem_size = 0M
# C'est ici qu'on désactive les erreurs de switch pour compiler sans soucis
build_flags =
    ${env:ZuluSCSI_RP2MCU.build_flags}
    -DZULUSCSI_MCU_RP2040
    -DCONTROL_BOARD
    -DSSD1306_NO_SPLASH
    -Wno-switch
